### ISSUE TITLE
Working with multiple scopes

### ISSUE THREAD

**Issue by carlesba** [cbochs/grapple.nvim#145]
I'm trying to work with multiple scopes at the same time and it works great for tagging and toggling the panel but it seems incomplete for other features like Telescope and status line.

Also, doesn't seem to work well when cycling with keymaps `:Grapple cycle_forward scope=xxx`. I couldn't make it to cycle with  2 different scopes using different keymaps. 

Is this an expected flow? Am I doing something wrong? What's the original idea behind scopes?

**Comment by cbochs** [comment]
> I'm trying to work with multiple scopes at the same time and it works great for tagging and toggling the panel but it seems incomplete for other features like Telescope and status line.

The telescope integration is relatively simple atm. I don't use grapple with telescope personally, but would gladly accept a PR to improve the existing integration.

> Also, doesn't seem to work well when cycling with keymaps :Grapple cycle_forward scope=xxx. I couldn't make it to cycle with 2 different scopes using different keymaps.

Would you mind giving a more concrete example? I can't seem to reproduce this on my side. If I have two scopes `git` and `global`, I am able to cycle through their tags just fine with:

```
Grapple cycle forward scope=git
Grapple cycle forward scope=global
```

> Is this an expected flow? Am I doing something wrong? What's the original idea behind scopes?

Have you had the change to read through the [Scopes](https://github.com/cbochs/grapple.nvim?tab=readme-ov-file#scopes) documentation (or, `:h grapple.nvim-scopes`)? I've seen some confusion on this topic. I'd love to hear what does not make sense so that I can improve the documentation 🙂

**Comment by carlesba** [comment]
I think I messed up with git and git_branches. My bad, it works fine. 

Thanks for the quick reply and sorry for the inconveniences.
