### ISSUE TITLE
feat: remember line number

### ISSUE THREAD

**Issue by KiLLeRRaT** [cbochs/grapple.nvim#72]
Hi All,

I'm using Grapple as a Harpoon replacement, and I have keys bound to jump to the files in my list:

Here is my config:
```lua
vim.keymap.set("n", "<leader>a", require("grapple").tag, {})
vim.keymap.set("n", "<leader>A", require("grapple").popup_tags, {})

vim.keymap.set("n", "<leader>h", function() require('grapple').select({ key = 1 }) end, { silent = true })
vim.keymap.set("n", "<leader>j", function() require('grapple').select({ key = 2 }) end, { silent = true })
vim.keymap.set("n", "<leader>k", function() require('grapple').select({ key = 3 }) end, { silent = true })
vim.keymap.set("n", "<leader>l", function() require('grapple').select({ key = 4 }) end, { silent = true })
```

Is there a way to have it such that when I press `<leader>h` for example, **that it remembers the line number, and jumps to the correct line in that file?**  I would love this to work while I'm inside the file already too, so if I scroll all the way to the top, and press `<leader>h`, it jumps to the line that I tagged.

Thanks for a very useful plugin!

**Comment by ShaolunWang** [comment]
I just took a look and it's caused by this line, and also the autocmd event that updates on quit in the `autocmds.lua` [file](https://github.com/cbochs/grapple.nvim/blob/ab274a3bfb674442d57fca05df866b71895853bc/lua/grapple/autocmds.lua#L18C1-L37C4):
https://github.com/cbochs/grapple.nvim/blob/ab274a3bfb674442d57fca05df866b71895853bc/lua/grapple/tags.lua#L102



change this to:
```lua
        if opts.toggle then
          cursor = vim.api.nvim_win_get_cursor(0)
        else
          cursor = vim.api.nvim_buf_get_mark(opts.buffer, '"')
        end
```
And add this in your nvim config file:
```lua
vim.api.nvim_clear_autocmds({group = "Grapple", event = 'BufLeave'})
```
